DROP TABLE IF EXISTS "clients" CASCADE;
DROP TABLE IF EXISTS "payments" CASCADE;
DROP TABLE IF EXISTS "events" CASCADE;
DROP TABLE IF EXISTS "quotes" CASCADE;

CREATE TABLE clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  contact text,
  email text,
  phone text,
  type text,
  category text,
  notes text
);

CREATE TABLE payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  empresa text,
  observacion text,
  monto numeric,
  tipo text
);

CREATE TABLE events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date,
  title text,
  type text,
  description text,
  time text
);

CREATE TABLE inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text,
  name text,
  category text,
  price numeric,
  stock numeric
);

CREATE TABLE quotes (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text,
  client_type text,
  location text,
  event_date date,
  event_name text,
  total numeric,
  status text,
  payment_date date,
  items jsonb,
  timing jsonb
);

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso total a anonimos" ON clients FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso total a anonimos" ON payments FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso total a anonimos" ON events FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso total a anonimos" ON inventory FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso total a anonimos" ON quotes FOR ALL USING (true) WITH CHECK (true);
